name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2.0.0
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
    - name: npm install, build, and test
      run: |
        yarn install --pure-lockfile
        yarn build
        yarn test
      env:
        CI: true
